name: odata_model_generator
description: A Dart package to generate models from OData metadata files.
version: 1.0.0
homepage: https://github.com/shubhamkarnalkar/odata_model_generator

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xml: ^6.3.0 # For XML parsing
  path: ^1.8.3 # For path manipulation
  args: ^2.4.2 # For command-line argument parsing (in bin)
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.6 # Required for json_serializable code generation
  json_annotation: ^4.8.1 # For the annotations in generated code
  json_serializable: ^6.7.1 # For the build_runner part
  test: ^1.24.0 # For testing
  lints: ^2.1.1